name: Test

on:
  schedule:
    - cron: '0 19 * * *'
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Redis
        uses: shogo82148/actions-setup-redis@v1
        with:
          redis-version: latest

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Test
        run: docker build --progress=plain --no-cache --network="host" --build-arg REDIS_ENABLED=true --build-arg REDIS_ADDR=127.0.0.1:6379 --target test .
        env:
          DOCKER_BUILDKIT: 1

